[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Google認証コールバック用のリダイレクト設定
[[redirects]]
  from = "/auth/google/callback"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"